### ISSUE TITLE
'dict' object has no attribute 'getint'

### ISSUE THREAD

**Issue by rogeroberholtzer** [trac-hacks/WikiReportMacro#2]
I just tried using the macro on Trac 1.2.2, and I get the following error message:

     Error: Macro WikiReport(1) failed

     'dict' object has no attribute 'getint'

This is in the Trac log:

    2017-09-11 08:22:38,089 Trac[formatter] ERROR: Macro WikiReport(1) failed for <Resource u'wiki:junk'>:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/Trac-1.2.2-py2.7.egg/trac/wiki/formatter.py", line 805, in _macro_formatter
        return macro.ensure_inline(macro.process(args))
      File "/usr/lib/python2.7/site-packages/Trac-1.2.2-py2.7.egg/trac/wiki/formatter.py", line 382, in process
        text = self.processor(text)
      File "/usr/lib/python2.7/site-packages/Trac-1.2.2-py2.7.egg/trac/wiki/formatter.py", line 354, in _macro_processor
      text)
      File "/usr/lib/python2.7/site-packages/WikiReport-0.2.0-py2.7.egg/wikireport/WikiReport.py", line 64, in expand_macro
        template, data, content_type = report._render_view(req, id)
      File "/usr/lib/python2.7/site-packages/Trac-1.2.2-py2.7.egg/trac/ticket/report.py", line 383, in _render_view
        page = req.args.getint('page', 1)
      AttributeError: 'dict' object has no attribute 'getint'

**Comment by rdnvndr** [comment]
Need more information. Please describe a playback scenary of error (the wiki page source, report and so on)

**Comment by rjollos** [comment]
The plugin is not compatible with Trac 1.2. It replaces `req.args` with a dictionary, whereas `req.args` needs to be an instance of `_RequestArgs`.
